"""T-402: PNG → LVGL 9.x C 배열 변환기 (lv_img_conv + Pillow 폴백).

단위구현계획서.md 제5장 [T-402] 8항 구현 내용을 따른다.
Node.js ``lv_img_conv`` 를 subprocess로 호출하고, CLI/의존성 누락 시
Pillow로 RGB565(16-bit) raw 바이너리를 ``lv_image_dsc_t`` C 소스로 직접 생성한다.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path
from typing import Callable

from PIL import Image

# LVGL 9.x RGB565: 픽셀당 2바이트.
BYTES_PER_PIXEL_RGB565 = 2
HEX_PER_LINE = 16

RunFn = Callable[..., subprocess.CompletedProcess]


def lv_img_conv_available() -> bool:
    """``npx`` 또는 ``lv_img_conv`` 실행 파일이 PATH에 있으면 True."""
    return shutil.which("npx") is not None or shutil.which("lv_img_conv") is not None


def _safe_c_ident(name: str) -> str:
    """C 식별자로 쓸 수 있는 stem을 만든다."""
    cleaned = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"img_{cleaned}"
    return cleaned or "img_asset"


def _rgb_to_rgb565_le(r: int, g: int, b: int) -> tuple[int, int]:
    """8-bit RGB → RGB565 little-endian (low, high)."""
    value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return value & 0xFF, (value >> 8) & 0xFF


def _pixels_to_rgb565_bytes(img: Image.Image) -> bytes:
    """PIL 이미지를 RGB565 little-endian 바이트열로 변환한다."""
    rgb = img.convert("RGB")
    raw = rgb.tobytes()  # contiguous RGB8
    out = bytearray(len(raw) // 3 * BYTES_PER_PIXEL_RGB565)
    j = 0
    for i in range(0, len(raw), 3):
        lo, hi = _rgb_to_rgb565_le(raw[i], raw[i + 1], raw[i + 2])
        out[j] = lo
        out[j + 1] = hi
        j += 2
    return bytes(out)


def _format_hex_array(data: bytes) -> str:
    """바이트열을 ``0xab, 0xcd, ...`` C 배열 본문으로 포맷한다."""
    lines: list[str] = []
    for i in range(0, len(data), HEX_PER_LINE):
        chunk = data[i : i + HEX_PER_LINE]
        parts = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {parts},")
    return "\n".join(lines)


def render_lvgl_c_source(
    *,
    symbol_name: str,
    width: int,
    height: int,
    pixel_data: bytes,
    color_format: str = "RGB565",
) -> str:
    """LVGL 9.x ``lv_image_dsc_t`` C 소스 문자열을 생성한다."""
    stride = width * BYTES_PER_PIXEL_RGB565
    data_size = len(pixel_data)
    cf = "LV_COLOR_FORMAT_RGB565" if color_format.upper() in ("RGB565", "CF_TRUE_COLOR") else (
        "LV_COLOR_FORMAT_RGB565"
    )
    map_name = f"{symbol_name}_map"
    hex_body = _format_hex_array(pixel_data)

    return f"""/*******************************************************************************
 * Image: {symbol_name}
 * Generated by EdgeCanvas image_converter (T-402)
 * Color format: {color_format} / 16-bit
 ******************************************************************************/

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t {map_name}[] = {{
{hex_body}
}};

const lv_image_dsc_t {symbol_name} = {{
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = {cf},
  .header.flags = 0,
  .header.w = {width},
  .header.h = {height},
  .header.stride = {stride},
  .data_size = {data_size},
  .data = {map_name},
}};
"""


def convert_with_pillow(
    png_path: Path | str,
    output_dir: Path | str,
    *,
    symbol_name: str | None = None,
    color_format: str = "RGB565",
) -> Path:
    """Pillow로 PNG → RGB565 ``lv_image_dsc_t`` C 파일을 생성한다."""
    src = Path(png_path)
    if not src.is_file():
        raise FileNotFoundError(f"PNG not found: {src}")

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    name = _safe_c_ident(symbol_name or src.stem)
    img = Image.open(src)
    width, height = img.size
    pixel_data = _pixels_to_rgb565_bytes(img)
    c_text = render_lvgl_c_source(
        symbol_name=name,
        width=width,
        height=height,
        pixel_data=pixel_data,
        color_format=color_format,
    )
    # 카드 12 예비 경로 표시용 주석
    c_text = c_text.replace(
        "Generated by EdgeCanvas image_converter (T-402)",
        "Generated by EdgeCanvas image_converter (T-402) / Pillow RGB565 fallback",
    )
    dest = out / f"{name}.c"
    dest.write_text(c_text, encoding="utf-8")
    return dest.resolve()


def _build_lv_img_conv_cmd(
    png_path: Path, output_dir: Path, *, color_format: str = "RGB565"
) -> list[str]:
    """lv_img_conv / npx 호출 인자 목록을 구성한다."""
    # LVGL img conv: CF_TRUE_COLOR ≈ RGB565 on little-endian MCUs.
    cf = "CF_TRUE_COLOR" if color_format.upper() == "RGB565" else color_format
    if shutil.which("lv_img_conv"):
        return [
            "lv_img_conv",
            str(png_path),
            "-f",
            "-c",
            cf,
            "-t",
            "c",
            "--output",
            str(output_dir),
        ]
    return [
        "npx",
        "--yes",
        "lv_img_conv",
        str(png_path),
        "-f",
        "-c",
        cf,
        "-t",
        "c",
        "--output",
        str(output_dir),
    ]


def try_convert_with_lv_img_conv(
    png_path: Path | str,
    output_dir: Path | str,
    *,
    symbol_name: str | None = None,
    color_format: str = "RGB565",
    run: RunFn | None = None,
) -> Path | None:
    """subprocess로 lv_img_conv를 호출한다. 성공 시 .c 경로, 실패 시 None."""
    if not lv_img_conv_available():
        return None

    src = Path(png_path)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    name = _safe_c_ident(symbol_name or src.stem)
    expected = out / f"{name}.c"
    # CLI가 stem 기반 이름을 쓰도록 입력을 맞춘다.
    work_png = src
    if src.stem != name:
        work_png = out / f"{name}.png"
        if not work_png.exists():
            work_png.write_bytes(src.read_bytes())

    cmd = _build_lv_img_conv_cmd(work_png, out, color_format=color_format)
    runner = run or subprocess.run
    try:
        result = runner(
            cmd,
            capture_output=True,
            check=False,
            timeout=120,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired):
        return None

    if getattr(result, "returncode", 1) != 0:
        return None

    # CLI가 이미 .c를 썼는지, 또는 stem 이름으로 썼는지 탐색
    if expected.is_file():
        return expected.resolve()
    candidates = sorted(out.glob("*.c"), key=lambda p: p.stat().st_mtime, reverse=True)
    for cand in candidates:
        text = cand.read_text(encoding="utf-8", errors="replace")
        if "lv_image_dsc_t" in text or "lv_img_dsc_t" in text:
            if cand.name != expected.name:
                cand.replace(expected)
            return expected.resolve()
    return None


def convert_png_to_c(
    png_path: Path | str,
    output_dir: Path | str,
    *,
    symbol_name: str | None = None,
    color_format: str = "RGB565",
    prefer_cli: bool = True,
    run: RunFn | None = None,
) -> Path:
    """PNG를 LVGL C 배열 파일로 변환한다.

    ``prefer_cli=True`` 이면 lv_img_conv subprocess를 먼저 시도하고,
    실패·누락 시 Pillow RGB565 폴백으로 항상 성공 경로를 유지한다(CLI 에러율 0%).
    """
    if prefer_cli:
        cli_path = try_convert_with_lv_img_conv(
            png_path,
            output_dir,
            symbol_name=symbol_name,
            color_format=color_format,
            run=run,
        )
        if cli_path is not None:
            return cli_path

    return convert_with_pillow(
        png_path,
        output_dir,
        symbol_name=symbol_name,
        color_format=color_format,
    )
