#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

/* Auto-generated by board_profile_mapper (T-301). Do not edit manually. */

#define BOARD_ID "esp32p4"
#define IDF_TARGET "esp32p4"
#define LCD_WIDTH 1024
#define LCD_HEIGHT 600
#define USE_MIPI_DSI 1
#define DISPLAY_CONTROLLER "ILI9488"
#define COLOR_DEPTH "RGB565"
#define TOUCH_IC "FT6236"


#endif /* BOARD_CONFIG_H */
