/*******************************************************************************
 * Image: t402_sample
 * Generated by EdgeCanvas image_converter (T-402) / Pillow RGB565 fallback
 * Color format: RGB565 / 16-bit
 ******************************************************************************/

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t t402_sample_map[] = {
  0x00, 0xf8, 0x00, 0xf8, 0x00, 0xf8, 0x00, 0xf8, 0x00, 0xf8, 0x00, 0xf8, 0x00, 0xf8, 0x00, 0xf8,
};

const lv_image_dsc_t t402_sample = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_RGB565,
  .header.flags = 0,
  .header.w = 4,
  .header.h = 2,
  .header.stride = 8,
  .data_size = 16,
  .data = t402_sample_map,
};
